apiVersion: release-notes/v2
kind: feature
area: traffic-management
releaseNotes:
  - |
    **Improved** istiod scalability in ambient mode by scoping XDS pushes from workload/service
    `Address` changes to only the affected waypoints, instead of pushing to all waypoints and proxies.
